### ISSUE TITLE
It's not good idea to keep secrets (passwords, tokens, etc...) in repository

### ISSUE THREAD

**Issue by jonasnobile** [Aleesssino/porkbyt-scraper-ts#1]

**Comment by Aleesssino** [comment]
Thanks for the heads-up @jonasnobile ! 
I know the importance of keeping secrets secure, and I’ve already fixed it in my last commit and cleaned up the Git history.

This repo was private at first, and I only made it public after my Bezrealitky account expired. I didn’t consider the risk at the time. I was trying to use an env variable for the username, but it was causing issues, so I ended up hardcoding it, thinking the repo would stay private. All sorted now though – appreciate you pointing it out!
